### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by distantobserver** [Llewellynvdm/Joomla-Cost-Benefit-Projection#10]
Hi,

Rachel was working with power Machine Tools Nam, belonging to clienta. She got an error message then could no longer use the site. 

I can't view the company in the administrator end now either (see attached screenshot) 

![image](https://cloud.githubusercontent.com/assets/7658109/14815974/51bbb4ea-0ba6-11e6-93dc-933df82e6640.png)

**Comment by Llewellynvdm** [comment]
This is due to the checkout feature. If another user opens an item it checks that item out to them like in a library, when you take a book it gets checked out to you. If you click close inside the item the system will check the item back in. But if the user forgets that they have the item and does not close it as they should. Then the item will remain checked out to them for a day, and the the system will automatically check it back in after that day has expired. So the error is just telling you that the related item is still checked out.
